-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 08:42:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE DATABASE IF NOT EXISTS `agrofinance` DEFAULT CHARACTER SET utf8;

CREATE SCHEMA IF NOT EXISTS `agrofinance` DEFAULT CHARACTER SET utf8 ;
USE `agrofinance` ;

CREATE TABLE IF NOT EXISTS `agrofinance`.`kategori_transaksi` (
  `kt_id_kategori` INT NULL AUTO_INCREMENT,
  `kt_nama_kategori` VARCHAR(255) NULL,
  PRIMARY KEY (`kt_id_kategori`),
  UNIQUE INDEX `nama_kategori_UNIQUE` (`kt_nama_kategori` ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS `agrofinance`.`transaksi` (
  `t_id_transaksi` INT NULL AUTO_INCREMENT,
  `t_jumlah` FLOAT NULL,
  `t_id_kategori_transaksi` INT NULL,
  `t_jenis` VARCHAR(45) NULL DEFAULT 'KAS',
  `t_bpu_attachment` VARCHAR(45) NULL,
  `t_debit_credit` TINYINT(1) NULL DEFAULT 0,
  `t_status` VARCHAR(45) NULL,
  `t_bon_sementara` VARCHAR(45) NULL,
  `t_is_rutin` TINYINT(1) NULL DEFAULT 0,
  `t_tanggal_transaksi` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `t_tanggal_modifikasi` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `t_tanggal_realisasi` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `t_nomor_bukti_transaksi` VARCHAR(45) NULL,
  `t_file_bukti_transaksi` VARCHAR(45) NULL,
  `t_pembebanan_id` INT NULL,
  PRIMARY KEY (`t_id_transaksi`));

CREATE TABLE IF NOT EXISTS `agrofinance`.`perusahaan` (
  `p_id_perusahaan` INT NULL AUTO_INCREMENT,
  `p_nama_perusahaan` VARCHAR(255) NULL,
  `p_alamat` TEXT NULL,
  PRIMARY KEY (`p_id_perusahaan`),
  UNIQUE INDEX `nama_perusahaan_UNIQUE` (`p_nama_perusahaan` ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS `agrofinance`.`karyawan` (
  `k_id_karyawan` INT NULL AUTO_INCREMENT,
  `k_nama_lengkap` VARCHAR(255) NOT NULL,
  `k_posisi` VARCHAR(45) NOT NULL,
  `k_nik` VARCHAR(255) NOT NULL,
  `k_role` VARCHAR(45) NOT NULL,
  `k_masih_hidup` TINYINT(1) NULL,
  PRIMARY KEY (`k_id_karyawan`),
  UNIQUE INDEX `nik_UNIQUE` (`k_nik` ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS `agrofinance`.`karyawan_kerja_dimana` (
  `kkd_id_karyawan_kerja_dimana` INT NOT NULL,
  `kkd_id_karyawan` INT NOT NULL,
  `kkd_id_perusahaan` INT NOT NULL,
  PRIMARY KEY (`kkd_id_karyawan_kerja_dimana`));

CREATE TABLE IF NOT EXISTS `agrofinance`.`pembebebanan` (
  `pbb_id` INT NULL AUTO_INCREMENT,
  `skema_pembebanan_json` LONGTEXT NULL,
  PRIMARY KEY (`pbb_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
